dict = {
    "grp_warn_no_reason":       "❗️️ {} xəbərdar edildi [{}/{}].",
    "grp_warn_reason":          "❗️️ {} has been warned [{}/{}] for <b>{}</b>",
    "log_warn_reason":          "❗️ <b>Xəbərdarlıq</b>\nİstifadəçi: {}\nAdmin: {}\nSəbəb: {}\nİstifadəçinin xəbərdarlıq sayı: {}/{}",
    "log_warn_no_reason":       "❗️ <b>Xəbərdarlıq</b>\nİstifadəçi: {}\nAdmin: {}\nİstifadəçinin xəbərdarlıq sayı: {}/{}",
    "log_new_user":             "➕ <b>Yeni üzv</b>\n-> {}",
    "log_new_user_closed":      "➕ <b>Yeni üzv</b>\n-> {}\nQrup bağlandı, Mən onu qrupdan atdım.",
    "grp_ban_reason":           "🚷 {} qadağan edildi, səbəb {}.",
    "log_ban_reason":           "🚷 <b>Qadağa</b>\nİstifadəçi: {}\nAdmim: {}\nSəbəb: {}",
    "grp_ban_no_reason":        "🚷 {} qadağan edildi.",
    "log_ban_no_reason":        "🚷 <b>Qadağa</b>\nİstifadəçi: {}\nAdmin: {}",
    "grp_mute_custom":          "🔇 {}  {} saat müddətində susduruldu.",
    "log_mute_custom":          "🔇 <b>Səssiz</b>\nİstifadəçi: {}\nAdmin: {}\nMüddət(saatla): {}",
    "grp_mute_default":         "🔇 {}  səbəbdən 1 saat müddətində susduruldu.Səbəb <b>{}</b>",
    "log_mute_default":         "🔇 <b>Səssiz</b>\nİstifadəçi: {}\nAdmim: {}\nSəbəb: {}\nMüddət(saatla): 1",
    "grp_kick_reason":          "❕ {}  bu səbəbdən qrupdan atıldı.Səbəb <b>{}</b>.",
    "log_kick_reason":          "❕ <b>Qovuldu</b>\nİstifadəçi: {}\nAdmin: {} \nSəbəb: {}",
    "grp_kick_no_reason":       "❕ {} qrupdan atıldı.",
    "log_kick_no_reason":       "❕ <b>Kick</b>\nTo: {}\nBy: {}",
    "grp_unban":                "✅ {} üçün qadağa qaldırıldı.",
    "log_unban":                "✅ <b>Qadağa qaldırıldı</b>\nİstifadəçi: {}\nAdmin: }",
    "grp_unwarn":               "❎ {} üçün xəbərdarlıq qaldırıldı.\nİstifadəçinin indi {} xəbərdarlığı var.",
    "log_unwarn":               "❎ <b>Qadağa qaldırıldı</b>\nİstifadəçi: {}\nAdmin: {} \nİstifadəçinin xəbərdarlıq sayı: {}/{}",
    "grp_unmute":               "🔊 {} səssizdən çıxarıldı.",
    "log_unmute":               "🔊 <b>Səssizdən çıxarıldı</b>\nİstifadəçi: {} \nAdmin: {}",
    "grp_info":                 "🙍‍♂️ <b>İstifadəçi Məlumatı</b>\nİstifadəçk: {}\nQrup İD: <code>{}</code>\nXəbərdarlıqlar: {}",
    "grp_new_helper":           "⛑ {} indi <b>Köməkçi</b> dir.",
    "log_new_helper":           "⛑ <b>Yeni köməkçi</b>\nİstifadəçi: {}\nAdmin: {}",
    "grp_rem_helper":           "⛑ {}  <b>Köməkçilər</b> dən uzaqlaşdırıldı.",
    "log_rem_helper":           "⛑ <b>Uzaqlaşdırılan Köməkçi</b>\nİstifadəçi: {}\nAdmin: {}",
    "grp_new_moderator":        "👷🏻 {} is now <b>Moderator</b>.",
    "log_new_moderator":        "👷🏻 <b>New Moderator</b>\nTo: {}\nBy: {}",
    "grp_rem_moderator":        "👷🏻 {} removed from <b>Moderators</b>.",
    "log_rem_moderator":        "👷🏻 <b>Removed Moderator</b>\nTo: {}\nBy: {}",
    "grp_new_manager":          "🛃 {} is now <b>Manager</b>.",
    "log_new_manager":          "🛃 <b>New Manager</b>\nTo: {}\nBy: {}",
    "grp_rem_manager":          "🛃 {} removed from <b>Managers</b>.",
    "log_rem_manager":          "🛃 <b>Removed Manager</b>\nTo: {}\nBy: {}",
    "bot_reload":               "✅ <b>Bot reloaded!</b>\nBy: {}",
    "bot_start_inactive_kick":  "☢️ <b>Passiv istifadəçilərin qovulması</b>\nBaşlatdı: {}\nMaksimum passiv gün sayı: {}",
    "bot_end_inactive_kick":    "☢️ <b>Passiv istifadəçilərin qovulması sonlardırıldı!</b>",
    "str_max_warns":            "Maksimum xəbərdarlıq həddini keçdi",
    "grp_staff_call":           "🆘 <i>Heyyət çağırıldı.</i>",
    "log_staff_call_reply":     "🆘 <b>Heyyət çağırıldı</b>\nÇağıran: {}\nSəbəbkar: {}\nMesaj: {}",
    "log_staff_call_noreply":   "🆘 <b>Heyyət çağırıldı</b>\nİstifadəçi: {}\nMesaj: {}",
    "grp_staff_title":          "🔰️ <b>Qrup Heyyəti</b> 🔰️",
    "grp_staff_founder":        "\n\n  👑 <b>Sahib</b>",
    "grp_staff_admins":         "\n\n  👮🏼 <b>Adminlər</b>",
    "grp_staff_moderators":     "\n\n  👷🏻 <b>Moderatorlar</b>",
    "grp_staff_managers":       "\n\n  🛃 <b>İdarəçilər</b>",
    "grp_staff_helpers":        "\n\n  ⛑ <b>Köməkçilər</b>",
    "grp_set_username":         "🌐  {}, zəhmət olmasa, Telegram Parametrlərinə daxil olaraq <b>istifadəçi adı</b>  quraşdır",
    "grp_scan_file":            "<i>Fayl skan edilir...</i>",
    "grp_scanned_safe":         "✅ Skan nəticəsi: Təhlükəsiz\nSiqnal {}/{}",
    "grp_scanned_warning":      "⚠️ Skan nəticəsi: Xəbərdarlıq\nSiqnal {}/{}",
    "grp_scanned_malware":      "🛑️ Skan nəticəsi: Virus\nSiqnal {}/{}",
    "grp_shorter_name":         "🌐 {}, zəhmət olmasa, Telegram Parametrlərinə daxil olaraq <b>qısa ad</b>  quraşdır.",
    "log_blacklist_word":       "🆎 <b>Qara Siyahı</b>\nİstifadəçi: {}",
    "str_forward":              "Hər hansı 1 kanaldan yönləndirildi",
    "str_porn":                 "18+ media",
    "str_offensive":            "Qadağan media",
    "grp_global_silence_on":    "🔇 <b>Səssiz rejim aktiv edildi!</b>\nİndi, yalnız adminlər mesaj yaza bilər.",
    "log_global_silence_on":    "🔇 <b>Səssiz rejim aktiv edildi</b>\nAdmin: {}",
    "grp_global_silence_off":   "🔊 <b>Səssiz rejim deaktiv edildi!</b>\nİndi, bütün istifadəçilər mesaj yaza bilər.",
    "log_global_silence_off":   "🔊 <b>Global Səssiz rejim deaktiv edildi</b>\nAdmin: {}",
    "grp_closegroup":           "🚷 <b>Qrup bağlandı!</b>\nİndi, indi heç kəs bu qrupa daxil ola bilməz.",
    "log_closegroup":           "🚷 <b>Qrup bağlandı</b>\nAdmin: {}",
    "grp_opengroup":            "✅ <b>Qrup açıldı!</b>\nİndi, hərkəs qrupa daxil ola bilər.",
    "log_opengroup":            "✅ <b>Qrup açıldı</b>\nAdmin: {}",
    "cmd_helper":               "/helper",
    "cmd_unhelper":             "/unhelper",
    "cmd_mod":                  "/mod",
    "cmd_unmod":                "/unmod",
    "cmd_manager":              "/mnager",
    "cmd_unmanager":            "/unmanager",
    "cmd_tell":                 "/tell",
    "cmd_reload":               "/reload",
    "cmd_kickinactive":         "/kickinactive",
    "cmd_warn":                 "/warn",
    "cmd_delwarn":              "/delwarn",
    "cmd_mute":                 "/mute",
    "cmd_kick":                 "/kick",
    "cmd_ban":                  "/ban",
    "cmd_unban":                "/unban",
    "cmd_unwarn":               "/unwarn",
    "cmd_unmute":               "/unmute",
    "cmd_info":                 "/info",
    "cmd_silenceon":            "/silenceon",
    "cmd_silenceoff":           "/silenceoff",
    "cmd_del":                  "/del",
    "cmd_staff":                "/staff",
    "cmd_rules":                "/rules",
    "cmd_pin":                  "/pin",
    "cmd_unpin":                "/unpin",
    "cmd_closegroup":           "/closegroup",
    "cmd_opengroup":            "/opengroup"
}
